   <link rel="stylesheet" href="../../css/kube.css">
	<link rel="stylesheet" href="../../css/styles.css">
	<link rel="stylesheet" href="../../css/font-awesome.min.css">
	<link rel="stylesheet" href="../../css/tipso.min.css">
	<link rel="stylesheet" href="../../css/animate.css">
	<link rel="stylesheet" href="../../css/alertify.css">
  <link rel="stylesheet" href="../../css/easyeditor.css">
  <link rel="stylesheet" href="../../css/Intimidatetime.min.css">
  <link rel="stylesheet" href="../../css/jquery.ezdz.css">